 element nonlinearBeamColumn 	1 		1 	   2 		$np 		$Sv2 		  $Try;	
 element nonlinearBeamColumn 	2 		4 	   5 		$np 		$Sv2 		  $Try;
 element nonlinearBeamColumn 	3 		7 	   8 		$np 		$Sv2 		  $Try;	
 element nonlinearBeamColumn 	4 		10 	   11 		$np 		$Sv2 		  $Try;
 element nonlinearBeamColumn 	5 		2 	   3 		$np 		$Sv2 		  $Try;	
 element nonlinearBeamColumn 	6 		5 	   6 		$np 		$Sv2 		  $Try;
 element nonlinearBeamColumn 	7 		8 	   9 		$np 		$Sv2 		  $Try;	
 element nonlinearBeamColumn 	8 		11 	   12 		$np 		$Sv2 		  $Try;
 element elasticBeamColumn 	  9 	 2	 	5 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  10 	 5	 	8 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  11 	 11	 	8 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  12 	 2	 	11 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  13 	 3	 	6 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  14 	 6	 	9 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  15 	 12	 	9 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;
 element elasticBeamColumn 	  16 	 3	 	12 	  $ASv1 $Es $Gs $ItSv1 $IySv1 $IzSv1 $Trz;